apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: devops-assignment3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: saramir04/flask-api:latest
        ports:
        - containerPort: 5000
