apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops-assignment3
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=
  MYSQL_DATABASE: aW52ZW50b3J5ZGI=
  MYSQL_USER: YXBwdXNlcg==
  MYSQL_PASSWORD: YXBwcGFzcw==
